jfrimmel/cargo-valgrind

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
- src/lib.rs
- src/metadata/mod.rs
- src/metadata/sample-metadata.json
- src/metadata/tests.rs
- src/metadata/version.rs
- src/tests.rs
This PR adds some functions, that can be used to get the paths of all executables of a crate. The crate itself is located by the path to the `Cargo.toml` file.
Note, that currently tests are not supported. Furthermore, workspaces are not supported as well; only the binaries of the specified manifest are returned.
> Find all executables of the crate

- Cargo.lock
- Cargo.toml
- src/lib.rs
The new function runs cargo and builds the executable. After a call to it the artifact is in place and can be run with valgrind.
> Added method to build the target executable

- Cargo.lock
- Cargo.toml
- src/lib.rs
Previously, the `binary()` function returned only the path to the different binaries of the crate. The information, which kind of binary (binary, example, benchmark, test) it is, is lost.
The new `target()` function provides this additional information. The old function is kept for compatibility, but is deprecated in favor of the new one.
> Provide target kinds along their paths

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
- src/lib.rs
- src/tests.rs
- src/valgrind_xml/tests.rs
This PR enables the support for running examples and benchmarks using `cargo-valgrind`.
The main application code (in `main.rs`) has undergone a massive refactoring.
> Support all binary targets

- src/bin/main.rs
Previously it was possible to specify `--example cstring` and if a bin-
ary (not an example) with that name exists, it was used.
This commit changes the behavior to the expected one.
> Fixed target comparison.

- src/lib.rs
Previously the fully path was compared, which lead to false negatives.
This commit compares only the type and the name.
> Properly compare two `Target`s.

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
Cargo passes the subcommand name as the first argument to the subcommand binary (refer to the [Cargo book](https://doc.rust-lang.org/stable/cargo/reference/external-tools.html#custom-subcommands)). This parameter was previously unexpected and thus this binary could not be used as a cargo subcommand.
The new command line interface expects this subcommand and thus works now as expected.
> Program usable as a cargo subcommand

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
- src/lib.rs
Provide better user feedback, if the program is used wrong or the `valgrind` command could not be executed.
> Better error messages

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/bin/main.rs
- src/lib.rs
This PR adds the `--features` flag to `cargo valgrind`. It can be used in the same way as the normal `cargo build` flag and builds the target with exactly those flags (and the default flags) enabled.
Note that there is no `--no-default-features` flags implemented (yet).
> Added --features flag

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
The last line of the output in the error cases is now the total number of bytes leaked.
> Print a summary of the leaked bytes.

- src/bin/main.rs
- src/lib.rs
This PR adds a new type `Valgrind`, similar to what #15 did. This is a step towards a more extensible crate, since there are no functions with changing signatures.
The old `valgrind` function is deprecated in favor of the new type.
> Make valgrind usage more extensible and future-proof

- Cargo.lock
- Cargo.toml
- src/bin/main.rs
This PR allows to specify the `--leak-check=<summary|full>` and `--show-leak-kinds=<set>` options, that match the normal valgrind parameters.
> Additional valgrind options

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/bin/main.rs
- src/lib.rs
Previously the `cargo valgrind` was not aware of build scripts and panicked due to a missing implementation of a handler for them. This PR filters out build scripts, witch prevents the panics, but also makes running build scripts inside cargo valgrind impossible (which should be a very rare case).
Note, that this won't fix the panic, if the crate contains integration tests.
Fixes #21.
> Don't panic on crates with build script

- src/lib.rs
As stated in the [Readme](TODO), the user is required to have valgrind in his PATH. As described in #25 this is not always the case, especially if there are different user accounts, which use the program. Some of them may have valgrind in the PATH, some may not. Those users, who don't have valgrind directly available, currently see the following output:
```bash
Finished dev [unoptimized + debuginfo] target(s) in 0.03s
Analyzing `target/debug/binary`
error: No such file or directory (os error 2)
```
which doesn't tell, which file is not found and requires them to search for it.
This PR improves the error message to give the following output:
```bash
Finished dev [unoptimized + debuginfo] target(s) in 0.03s
Analyzing `target/debug/binary`
error: valgrind executable not found in `PATH` (No …
```
> Better error message if valgrind executable is not found

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/bin/main.rs
- src/lib.rs
This PR introduces the ability to pass user flags to the analyzed binary after `--`, similar to what can be done with the normal `cargo run --`.
Closes #27.
Closes #19.
> Support user flags

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/panic.rs
This commit introduces a new, optional dependency on `textwrap`, which
is used for wrapping the panic and help messages, if the feature is
available.
> Automatically wrap text in long user output

- src/main.rs
- src/panic.rs
- src/valgrind/mod.rs
If the valgrind binary outputs anything, that `cargo-valgrind` cannot handle, there is an error output.
Currently, that output looks like that:
```
error: unexpected valgrind output: custom: 'missing field `auxwhat`'
```
This looks like the run binary had an error or something. It is not immediately obvious, that there is an implementation error in `cargo-valgrind`.
This PR changes the error output to a panic with a custom message:
```
Oooops. cargo valgrind unexpectedly crashed. This is a bug!
This is an error in this program, which should be fixed. If you can, please submit a
bug report at
https://github.com/jfrimmel/cargo-valgrind/issues/new/choose
To make fixing the error more easy, please provide the information below as well as
additional information on which project the error …
```
> More helpful panic message on invalid/unknown XML

- .github/workflows/ci.yaml
- .github/workflows/msrv.yaml
- .github/workflows/style.yaml
There are three workflows in place:
- the basic CI workflow, that builds the crate on multiple platforms and
tests the program on linux (where valgrind can be easily installed)
- the MSRV test
- the style test (formatting and linting)
> Add GitHub CI workflows

- .github/workflows/style.yaml
Previously, there was a PR comment if there were no errors but at least one dependency. This commit fixes it by ignoring all lines before the first actual clippy output.
Fixes #47.
> Fix the output of dependencies

- README.md
- src/valgrind/mod.rs
ex: `VALGRINDFLAGS=--tool=dhat cargo valgrind test`
Fixes #37.
> add VALGRINDFLAGS env var

- .github/workflows/deploy.yml
To speed up CI jobs that use `cargo-valgrind` and avoid running the `cargo install cargo-valgrind` command, I think it would be helpful to automatically deploy `cargo-valgrind` on `Linux`, `MacOS` and `Windows` through `GithHub Actions`. The action is triggered when a new tag is added and pushed.
I hope this is appreciated, thanks in advance for your review!
> Deploy cargo-valgrind automatically

- src/valgrind/mod.rs
looks like the linter didn't like my last PR. I don't tend to run with `--all` so I didn't notice.
Sorry about that, here are some fixes
valgrind doesn't take well to empty arguments on Linux as it turns out so I fixed that too (tested originally on a mac).
> fix args and lint issues

- src/valgrind/mod.rs
valgrind options were not parsed correctly when specifying more than one option
> fix valgrind options parsing: use space as delimiter

- src/main.rs
This improves the output of cases like #74 by outputting the additional information present in the valgrind output. The results are looking like this:
```text
Error Invalid read of size 4
Info main stack trace (user code at the bottom)
at core::fmt::num::imp::<impl core::fmt::Display for i32>::fmt (num.rs:317)
at core::fmt::num::<impl core::fmt::Debug for i32>::fmt (num.rs:195)
at <&T as core::fmt::Debug>::fmt (mod.rs:2368)
at {closure#0} (builders.rs:505)
at {closure#0}<core::fmt::builders::{impl#6}::entry::{closure_env#0}> (builders.rs:430)
at and_then<(), core::fmt::Error, (), core::fmt::builders::{impl#5}::entry_with::{closure_env#0}<core::fmt::builders::{impl#6}::entry::{closure_env#0}>> (result.rs:1346)
at entry_with<core::fmt::builders::{impl#6}::entry::{closure_env#0}> …
```
> Display additional ("aux") information and stacks

- .github/workflows/ci.yaml
- .github/workflows/deploy.yml
- .github/workflows/msrv.yaml
- .github/workflows/release.yaml
- .github/workflows/style.yaml
- Update to the latest version of GitHub Actions checkout (v4)
- run CI workflows on push instead on pull requests
> Update CI definitions

- .github/workflows/release.yaml
The [latest release workflow] failed due to the branch protection rules, which prevents changes to the default branch without a pull request. The exception for deploy keys were not relevant, as there is no deploy key used as of now. Therefore this commit uses a newly added deploy SSH key (RSA).
[latest release workflow]: https://github.com/jfrimmel/cargo-valgrind/actions/runs/10904155821/job/30260156202
> Install the deploy SSH keys

- .gitignore
- CHANGELOG.md
- src/main.rs
- tests/corpus/Cargo.toml
- tests/corpus/issue-13.rs
- tests/regression.rs
This commit checks for a specific valgrind output string occurring when a potential stack overflow is detected. The output is "parsed" a bit, in order to produces a nicer user experience. The output looks like this:
```text
$ cargo valgrind run --manifest-path tests/corpus/Cargo.toml --bin issue-13
Error: looks like the program overflowed its stack
Info: valgrind says:
==1937526== Stack overflow in thread #1: can't grow stack to 0x1ffe801000
==1937526== Stack overflow in thread #1: can't grow stack to 0x1ffe801000
==1937526== Stack overflow in thread #1: can't grow stack to 0x1ffe801000
==1937526==  If you believe this happened as a result of a stack
==1937526==  overflow in your program's main thread (unlikely but
==1937526==  possible), you can try to increase the size of the …
```
> Add proper stack overflow detection

- src/driver.rs
This fixes an issue where rustc cannot be found since the cargo and rustc binaries are in separate directories.
You should probably fix the clippy lints!
> Use `cargo version -v` instead of `rustc -vV` when obtaining host triple

- .github/workflows/msrv.yaml
- src/driver.rs
- tests/corpus/issue-74.rs
While it makes sense to be able to build this project with old versions of Rust (and this is actually ensured), it also necessary to be able to _actually run_ the tool successfully. Therefore this commit introduces a fallback for older Rust versions, where `cargo` does not include the `host:`-field in the output (the 1.51 cargo outputs):
```text
cargo 1.51.0 (43b129a20 2021-03-16)
release: 1.51.0
commit-hash: 43b129a20fbf1ede0df411396ccf0c024bf34134
commit-date: 2021-03-16
```
This PR ensures, that the MSRV can actually run by running the tests in this repository with the MSRV-cargo as well.
> Follow-up to #77: make sure, that everything works with current MSRV

- src/driver.rs
The old code was very messy for multiple reasons: the code worked almost entirely with `Vec<u8>` (a.k.a. byte strings) instead of actual strings, and thus needed to perform all string operations by hand. The search was also linear (although the performance penalty is negligible in this case). Another bad thing is, that the code always executed the fallback path of querying `rustc -vV` even if the normal path would have worked (which are the majority of cases), therefore the code needed a redesign.
This PR pulls the search over a specific command output out into its own function and runs the primary path first and only runs the fallback path if necessary. This makes the code much easier to read and under- stand. The new function also works on strings, making its implementation much …
> Cleanup host-lookup in driver code

- .github/workflows/ci.yaml
- .github/workflows/msrv.yaml
- .github/workflows/style.yaml
I have the hope, that this will allow to run workflows from contributors submitting a pull request from a fork. This is a little bit annoying for myself, as pushes from this repository are built and then, when a PR is opened, everything is rebuilt. [Others face the same issue](https://github.com/orgs/community/discussions/26276#discussioncomment-3251151).
> Also run GitHub workflows on pull requests

- Cargo.toml
* [Use more concise way of specifying dependencies](https://github.com/jfrimmel/cargo-valgrind/commit/4fb4b0617cb03c1187bd8757b6bac123ae60052a)
* [Fix spelling of `subcommand`](https://github.com/jfrimmel/cargo-valgrind/commit/5857cb1195c2c8ee25889bd31ce3482714f1a426)
* [Exclude some directories from published artifact](https://github.com/jfrimmel/cargo-valgrind/commit/eedf5b8f3da2b476badf5f039e82c7bc82b524fc)
* [Format `Cargo.toml`](https://github.com/jfrimmel/cargo-valgrind/commit/6569c2b5b5800e10523df66525aa84aed9e05583)
No functional changes intended :wink:
> Clean up the `Cargo.toml` manifest

- .github/workflows/ci.yaml
- .github/workflows/style.yaml
- CHANGELOG.md
- src/valgrind/xml/mod.rs
See the individual commits for details.
> Chore: fix clippy lints and some minor CI/documentation updates

- .github/workflows/beta.yaml
Without valgrind installed, executing the tests will obviously fail, so the first (any up to now only) run of the [workflow] created issue #113 due to test failures caused by missing valgrind.
[workflow]: https://github.com/jfrimmel/cargo-valgrind/actions/runs/12452939892/job/34762500879
Fixes #113.
> Install valgrind in beta compiler test

- .github/workflows/beta.yaml
- .github/workflows/ci.yaml
- .github/workflows/deploy.yml
- .github/workflows/msrv.yaml
As detected on the periodic beta-test-job, the installation of valgrind may fail. This is caused by not running `apt-get update` beforehand. While doing this change, the non-stable CLI of `apt` is replaced with the stable `apt-get`.
> Make sure, that apt-based installations work

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
Declare MSRV and update dependencies with new MSRV-aware resolver (run with 1.85).
> Manifest/dependency Maintenance

- suppressions/rust-1.83
- suppressions/rust-1.86
Apparently, the hashes in the mangled function names are different in each build of Rust (e.g. Rust 1.86.0-beta.5 and 1.86.0-beta.7 produce different ones, 1.87.0 has different ones again). Therefore the hashes get replaced with a wildcard in this commit.
This makes the suppressions applicable for all Rust 1.86 betas as well as 1.86.0 itself.
Fixes #123.
> Remove hashes in Valgrind suppressions

- suppressions/rust-1.86
Not sure what stdlib change caused this, but I'm seeing `impl#16` instead of `impl#14` in recent nightlies, see e.g. [this CI job](https://github.com/iex-rs/lithium/actions/runs/18269820778/job/52010343643).
> Update suppression list for recent nightly
